### ISSUE TITLE
Content Authorship Violation

### ISSUE THREAD

**Issue by ivan-kleshnin** [8bithemant/Mindmap-Full-Stack#1]
Hi @8bithemant. I see you've copied my Fullstack Mindmap.
I'm glad you liked it but, please, add a link to the original repository with a corresponding note.
This content is distributed under CCA v3 license: https://creativecommons.org/licenses/by/3.0/deed.en (added a note to the original repo).

**Comment by 8bithemant** [comment]
Yes ,
Sorry for the content copy but I wanted to add more maps and creating a collection of such maps and I will have to link you in my repo and look there I added a link to your GitHub profile and a link to your official repo and the note too.

**Comment by ivan-kleshnin** [comment]
Thanks, Hemant. Have a good weekend!
